version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages"
    schedule:
      interval: "weekly"